name: Build
on:
  push:
    branches:
      - tespkg
      - 'v**'
    tags:
      - *
  pull_request:
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t tespkg/grafana:${GITHUB_SHA} .
          docker tag tespkg/grafana:${GITHUB_SHA} tespkg/grafana:latest
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            docker tag tespkg/grafana:${GITHUB_SHA} tespkg/grafana:${{ github.ref_name }}
          fi

      - name: Push image to gitlab registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_TOKEN }} --password-stdin
          docker push tespkg/grafana
