name: Build
on:
  push:
    branches:
      - tespkg
      - 'v**'
    tags:
      - v*.*.*

jobs:
  build_and_push_image:
    name: build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build -t tespkg/grafana:${GITHUB_SHA} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag & Push docker image
        run: |
          docker tag tespkg/grafana:${GITHUB_SHA} tespkg/grafana:latest
          docker push tespkg/grafana:${GITHUB_SHA} tespkg/grafana:latest
          echo "pushed tespkg/grafana:${GITHUB_SHA}"
          # tag
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            docker tag tespkg/grafana:${GITHUB_SHA} tespkg/grafana:${{ github.ref_name }}
            docker push tespkg/grafana:${{ github.ref_name }}
            echo "pushed tespkg/grafana:${{ github.ref_name }}"
          fi
