name: Build
on:
  push:
    tags:
      - v*.*.*

jobs:
  tag_docker:
    name: Tag docker image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag docker new version
        run: |
          docker manifest create tespkg/grafana:${{ github.ref_name }} tespkg/grafana:${GITHUB_SHA}
          docker manifest push tespkg/grafana:${{ github.ref_name }}
